### ISSUE TITLE
Suppress unneeded/broken commands

### ISSUE THREAD

**Issue by mjtko** [alces-software/userware#13]
Would be useful to disable `import`, `export` and `support` commands for the sandbox CLI.

Perhaps implement a flag that can be supplied to the sandbox CLI to make these commands unavailable?

**Comment by mjtko** [comment]
Note that we'd still want access to `import` and `export` outside of the sandbox CLI (i.e. we would manually log in and perform `export`/`import` operations for now).

**Comment by bobwhitelock** [comment]
@DavidMarchant ideas for how to do this: we already have a function which we use to check if we're in the sandbox:

https://github.com/alces-software/userware/blob/be60b773e62c6700fc87587d9dde9e5d977ea4cc/directory/cli/src/import_export.py#L131-L137

and the different commands are defined within `add_commands` functions in the different modules. So I think we may be able to prevent defining these commands by just adding an early return to these functions in these modules, like this:

```python
def add_commands(directory):
    return if utils.in_sandbox()
    ...
```

I also mentioned removing the existing use of `in_sandbox` since once this is done it can never be hit, but thinking about it more it may be worth just keeping this for now in case we later re-allow access to `import` and `export` within the sandbox.

**Comment by DavidMarchant** [comment]
Ok, that's done, thanks both :)
