### ISSUE TITLE
Audit trail logs

### ISSUE THREAD

**Issue by mjtko** [alces-software/userware#14]
Not sure whether this is already present, but we could do with a log file that shows what command has been run at what time.

NB. suppress passwords in logs

**Comment by mjtko** [comment]
Look into logging all environment variables with the prefix `FC_`, log timestamp, log success/failure?

**Comment by bobwhitelock** [comment]
@DavidMarchant ideas for implementing this:

Currently we record the original `directory` command run every time this runs an `ipa` command which succeeds:

https://github.com/alces-software/userware/blob/be60b773e62c6700fc87587d9dde9e5d977ea4cc/directory/cli/src/ipa_utils.py#L72-L91

For an audit trail we want somewhat similar behaviour, and the `utils.original_command` function will likely also be useful for getting the original command run (aside: Click obscures this once a command is executing which is why this function exists; it should hopefully _just work_ for what you're doing). I also imagine we'll want some differences between the audit trail and import/export log, such as:

1. We probably want to log every `directory` command run for the log, so may want to do this at the top level; maybe here:

https://github.com/alces-software/userware/blob/be60b773e62c6700fc87587d9dde9e5d977ea4cc/directory/cli/src/directory.py#L27-L33

2. We probably want to log other data as well as the `directory` command, including current time, arbitrary `FC_` prefixed environment variables, and possibly whether the command succeeded - I'd suggest using a standard format like CSV for the file, which should make working with this more robust and adding new fields as needed simpler (see https://docs.python.org/3.5/library/csv.html).

Re: passing the `FC_`-prefixed environment variables through SSH to the directory appliance, it looks like this is possible: https://superuser.com/a/702751/755605. Specifically (and without trying this out) I think we'll want to:

1. Set `SendEnv FC_*` in `~/.ssh/config` on the machine running the directory `ssh` command, and then set any `FC_USER`, `FC_ORGANIZATION` etc. variables we want when running the `ssh` command (relevant to @benarmston).

2. Set `AcceptEnv FC_*` in `/etc/ssh/sshd_config` on every `directory` appliance.

3. Pick up any/all `FC_*` environment variables when logging commands in the `directory` CLI.

**Comment by mjtko** [comment]
@ColonelPanicks: can you make a note to add/actually add step (2) above to the install/build steps for the directory/IPA appliance please?

**Comment by benarmston** [comment]
@bobwhitelock I was just about to mention points (1) and (2) to you :-)

**Comment by DavidMarchant** [comment]
Just to clarify, are we wanting to store commands that don't change any data? (list and view cmds)? 
Also will we have to account for the env vars changing & having to be re-accessed during runtime?

**Comment by mjtko** [comment]
Might as well store all commands IMO. If nothing else that would also give useful usage metrics.

Re: environment variables changing during runtime: unless userware is modifying them itself, that shouldn't happen, so nothing to worry about afaics.

**Comment by DavidMarchant** [comment]
Ok cheers Mark, I'll sort that tomorrow

**Comment by ColonelPanicks** [comment]
In reference to:
> Set AcceptEnv FC_* in /etc/ssh/sshd_config on every directory appliance.

This configuration and other steps to setup the FC appliance are currently in an S3 script here - https://s3-eu-west-1.amazonaws.com/flightconnector/directory/resources/infra01-setup.sh

**Comment by ColonelPanicks** [comment]
Closed by #19
